name: Bug Report
description: Spotted a bug? Let's fix it!
title: "Feature X fails when Y happens"
body:
  - type: markdown
    attributes:
      value: |
        👋 Hello! Thanks for helping us make Serenity BDD better for everyone!
        
        If you saw a bug, please provide as much information as possible to help us find it and fix it.

  - type: textarea
    id: bug-description
    attributes:
      label: What happened?
      description: |
        What error or unexpected behaviour did you observe?
        Did you see any error messages?
        Are there any execution logs you can share?
    validations:
      required: false

  - type: textarea
    id: expected-behaviour
    attributes:
      label: What did you expect to happen?
    validations:
      required: false

  - type: input
    id: serenity-bdd-versions
    attributes:
      label: Serenity BDD version
      description: |
        What **Serenity BDD modules** and **what versions** are you using? Are you on the [latest version](https://github.com/serenity-bdd/serenity-core#what-is-the-latest-stable-version-i-should-use)?
    validations:
      required: true

  - type: input
    id: java-version
    attributes:
      label: JDK version
      description: |
        What version of Java are you using?
        To find out, run `java -version`
    validations:
      required: true

  - type: textarea
    id: execution-environment
    attributes:
      label: Execution environment
      description: |
        What **operating system** are you using?
        What **web browser** are you using?
        Are there any runtime dependencies that might be causing the issue?
    validations:
      required: false

  - type: textarea
    id: reproducible-example
    attributes:
      label: How to reproduce the bug.
      description: |
        The easier you make it for us to reproduce the issue, the more likely we will fix it.
        Please provide a [minimal reproducible example](https://en.wikipedia.org/wiki/Minimal_reproducible_example) using one of the [Serenity BDD project templates](https://github.com/serenity-bdd?q=template&type=all&language=&sort=).
      placeholder: |
        Link to your GitHub repository demonstrating the issue: ...
        
        Steps to reproduce:
        - ...
    validations:
      required: true

  - type: dropdown
    attributes:
      label: How can we make it happen?
      description: |
        
        Serenity BDD is an open-source project, and we greatly appreciate your contribution to help make it better. 
        Please be aware that while we may be able to address this issue quickly, especially if it aligns with other work 
        we are currently doing, there is no SLA or guarantee that it will ever be fixed. If the issue is valuable for you 
        and your project and you want to improve the chances of getting it fixed, you have several options. 
        You can dive into the code yourself (with our guidance), hire a third party to fix it, or **[Hire the Serenity BDD team](https://www.serenity-dojo.com/serenity-bdd-enterprise-support)** 
        to do it for you. We're here to help in any way we can!
        
        I would like to:
      options:
        - Work on this myself and propose a PR (with Serenity BDD team guidance)
        - Hire the Serenity BDD team
        - Add it to the Serenity BDD backlog and wait for a volunteer to pick it up
    validations:
      required: true
