blank_issues_enabled: true
contact_links:
  - name: Serenity BDD Community Chat
    url: https://matrix.to/#/#serenity-bdd_serenity-core:gitter.im
    about: "Ask and answer questions about Serenity BDD and become part of our Community!"
